### ISSUE TITLE
Add option to convert maf file to other file format(s)

### ISSUE THREAD

**Issue by johannesnicolaus** [oist/plessy_pairwiseGenomeComparison#22]
I think https://nf-co.re/modules/last_mafconvert can be used to add functionality to convert maf files to other file formats

**Comment by charles-plessy** [comment]
It is going to be in _pairgenomealign_ unless there is a strong need to have it here.  Link to work in progress: https://github.com/oist/LuscombeU_nfcore_pairgenomealign_fork/tree/maf-convert
